CREATE VIEW VW_TRANSACTION_DLD AS

SELECT
ROW_ID,INSTANCE_DATE,GROUP_EN,IS_OFFPLAN_EN,IS_FREE_HOLD_EN,USAGE_EN,AREA_EN,PROJECT_EN,PROP_SB_TYPE_EN,ACTUAL_AREA,ROOMS_EN,PARKING,TRANS_VALUE,PRICE_PER_M
FROM [Transactions-2026-01-01]
WHERE AREA_EN = 'Warsan First'
OR AREA_EN = 'INTERNATIONAL CITY PH 1' 
OR AREA_EN ='DUBAI SOUTH' 
OR AREA_EN ='Wadi Al Safa 3' 
OR AREA_EN ='Wadi Al Safa 4'
OR AREA_EN ='Warsan Fourth'
OR AREA_EN ='MAJAN'
OR AREA_EN ='Wadi Al Safa 5' 
OR AREA_EN ='Wadi Al Safa 7' 
OR AREA_EN ='Wadi Al Safa 2' 

---------------------------------------------------------------------------------------------------------------------------------------------

SELECT 
COUNT(ROW_ID) AS TOTAL_TRANSACTION,
SUM(TRANS_VALUE) AS TOTAL_VALUE_SELLING,
COUNT(AREA_EN) AS TOTAL_AREAS,
COUNT(PROJECT_EN) AS TOTAL_PROJECTS ,
AVG(PRICE_PER_M) AS AVGPRICE_PER_M
FROM VW_TRANSACTION_DLD 

---------------------------------------اسعار المساحه بالمشاريع --------------------------------------

SELECT 
COUNT( ROW_ID) TOTAL_PROPERTY ,
AVG(PRICE_PER_M) AS AVGPRICE_PER_M  ,
ROOMS_EN,
RANK () OVER (ORDER BY AVG(PRICE_PER_M) DESC ) AS RANKPRICE

FROM VW_TRANSACTION_DLD 
GROUP BY ROOMS_EN


----------------------------اجمالي مبيعات وعدد وحدات مباعة لكل مشروع ------------------------------

SELECT 

COUNT( ROW_ID) TOTAL_PROPERTY ,
SUM(TRANS_VALUE) AS TOTAL_VALUE_SELLING,
PROJECT_EN
FROM VW_TRANSACTION_DLD 
GROUP BY PROJECT_EN
ORDER BY TOTAL_VALUE_SELLING DESC 

-------------------------العقارات الاكثر مبيعا من حيث النوع--------------------------------------
SELECT
ROOMS_EN,
SUM(TRANS_VALUE) AS TOTAL_VALUE_SELLING,
COUNT( ROW_ID) TOTAL_PROPERTY
FROM VW_TRANSACTION_DLD
GROUP BY ROOMS_EN



------------------------------العقارات في المناطق -------------------------
SELECT
AREA_EN,
ROUND(SUM(TRANS_VALUE),2) AS TOTAL_VALUE_SELLING,
ROUND(AVG(PRICE_PER_M)  , 2)AS AVGPRICE_PER_M ,
COUNT( ROW_ID) TOTAL_PROPERTY
FROM VW_TRANSACTION_DLD
GROUP BY AREA_EN
ORDER BY AVGPRICE_PER_M DESC

----------------------------متوسط سعر المتر حسب نوع العقار بالمتر المربع -------------------------
SELECT
ROOMS_EN,
COUNT(ROW_ID) AS TOTAL_PROPERTY,
ROUND(AVG(TRANS_VALUE/ NULLIF(ACTUAL_AREA,0)),2) AS AVG_PRICE_PERTYPE,
ROUND(MAX(TRANS_VALUE/ NULLIF(ACTUAL_AREA,0)),2) AS MAX_PRICE_PERTYPE,
ROUND(MIN(TRANS_VALUE/ NULLIF(ACTUAL_AREA,0)),2) AS MIN_PRICE_PERTYPE
FROM VW_TRANSACTION_DLD
GROUP BY ROOMS_EN
ORDER BY AVG_PRICE_PERTYPE DESC 



---------------------------المعاملات الشهرية للمناطق --------------------------


SELECT
MONTH(INSTANCE_DATE) AS BY_MONTH,
YEAR(INSTANCE_DATE) AS BY_YEAR,
COUNT(ROW_ID) AS TOTAL_POREPRTY,
SUM(TRANS_VALUE) AS Total_Value,
AREA_EN
FROM VW_TRANSACTION_DLD
GROUP BY AREA_EN,MONTH(INSTANCE_DATE),YEAR(INSTANCE_DATE)
ORDER BY TOTAL_POREPRTY DESC           